version: 2
updates:

- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: "weekly"
  groups:
    build-dependencies:
      # Critical build/release dependencies
      patterns:
        - "build"
        - "hatchling"
        - "pip-tools"
    test-dependencies:
      # Python dependencies that are only pinned to ensure test reproducibility
      patterns:
        - "mypy"
        - "ruff"
        - "tox"

- package-ecosystem: "pip"
  # Disabled: this is managed in update-pinned-dependencies.yml
  directory: "/repo/install"
  open-pull-requests-limit: 0
  schedule:
    interval: "weekly"

- package-ecosystem: "pip"
  directories:
    - "/signer"
    - "/repo"
  schedule:
    interval: "weekly"
  groups:
    pyproject-dependencies:
      # Dependency ranges set in {signer,repo}/pyproject.toml
      patterns:
        - "*"

- package-ecosystem: "github-actions"
  directories:  
    - "/"
    - "/actions/create-signing-events/"
    - "/actions/online-sign/"
    - "/actions/signing-event/"
    - "/actions/test-repository/"
    - "/actions/update-issue/"
    - "/actions/upload-repository/"
  schedule:
    interval: "daily"
    time: "10:25"
