version: 2
updates:

- package-ecosystem: "pip"
  directory: "signer/"
  schedule:
    interval: "daily"
    time: "10:00"

- package-ecosystem: "pip"
  directory: "repo/"
  schedule:
    interval: "daily"
    time: "10:00"

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
    time: "10:00"
