version: 2
updates:

- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: "weekly"
  groups:
    build-dependencies:
      # Critical build/release dependencies
      patterns:
        - "build"
        - "hatchling"
        - "pip-tools"
    test-dependencies:
      # Python dependencies that are only pinned to ensure test reproducibility
      patterns:
        - "mypy"
        - "ruff"
        - "tox"

- package-ecosystem: "pip"
  directory: "signer"
  schedule:
    interval: "weekly"
  groups:
    pyproject-dependencies:
      # Dependency ranges set in pyproject.toml
      patterns:
        - "*"

- package-ecosystem: "pip"
  directory: "repo"
  schedule:
    interval: "weekly"
  groups:
    pyproject-dependencies:
      # Dependency ranges set in pyproject.toml
      patterns:
        - "*"

- package-ecosystem: "pip"
  # Disabled: this is managed in update-pinned-dependencies.yml
  directory: "repo/install"
  open-pull-requests-limit: 0
  schedule:
    interval: "weekly"


- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
    time: "10:25"

- package-ecosystem: "github-actions"
  directory: "actions/create-signing-events/"
  schedule:
    interval: "daily"
    time: "10:25"

- package-ecosystem: "github-actions"
  directory: "actions/online-sign/"
  schedule:
    interval: "daily"
    time: "10:25"

- package-ecosystem: "github-actions"
  directory: "actions/signing-event/"
  schedule:
    interval: "daily"
    time: "10:25"

- package-ecosystem: "github-actions"
  directory: "actions/upload-repository/"
  schedule:
    interval: "daily"
    time: "10:25"
