name: Lint & test

on:
  push:
  pull_request:

permissions: {}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c

    - uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1
      with:
        python-version: "3.11"
        cache: 'pip'
        cache-dependency-path: "**/pyproject.toml"

    - name: Install system dependencies for e2e test
      run: |
        sudo apt-get install libfaketime softhsm2
        echo "PYKCS11LIB=/usr/lib/softhsm/libsofthsm2.so" >> $GITHUB_ENV

    - name: Install tox
      run: python -m pip install tox

    - name: Lint
      run: tox -m lint

    - name: Repository unit tests
      run: tox -e test-repo

    - name: End-to-end tests
      run: tox -e test-e2e
